In [18]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a.size)

print(a.shape)

b = np.array([[1,2], [2,4], [3,6], [4,8]])

print(b.size)

print(b.shape)

c = np.array(range(1,16,1)).reshape(3, 5)
# equal c = np.array(range(15)).reshape(3, 5)

print(c.size)
print(c.shape)
print(c)


d= np.zeros((3,4))

print(d)

e = np.ones((3,5))

print(e)

f = np.empty((2,3))
print(f)


h = np.arange(15)
print(h)

5
(5,)
8
(4, 2)
15
(3, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[6.94529736e-310 6.94529736e-310 6.94525968e-310]
 [6.94525964e-310 6.94525970e-310 6.94525964e-310]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
